

# This file was *autogenerated* from the file main.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_20 = Integer(20); _sage_const_9 = Integer(9)
def coprime(a, b):
    return gcd(a, b) == _sage_const_1 


def pairwise_coprime(xs):
    if xs:
        h, *t = xs
        return all(coprime(h, x) for x in t) and pairwise_coprime(t)
    return True


def solve(n, xs):
    ys = []
    for (i, a) in enumerate(xs):
        residues = [a] + [_sage_const_1 ] * i
        moduli = [n] + ys
        r = crt(residues, moduli)
        print(residues, moduli, r)
        ys.append(r)
    return ys


def speed(n, xs):
    if xs:
        h, *t = xs
        ys = [h]
        for x in t:
            y = x
            while not pairwise_coprime([y, *ys]):
                y += n
            ys.append(y)
        return ys
    return []


n = _sage_const_20 
# xs = [3, 7, 9]
xs = [_sage_const_9 ] * _sage_const_20 

assert all(coprime(n, x) for x in xs)
ys = speed(n, xs)
show(ys)
assert pairwise_coprime(ys)

